plugins {
    id 'com.android.application'
}

android {
    namespace 'com.roniel.escrevemais'
    compileSdk 35

    defaultConfig {
        applicationId 'com.roniel.escrevemais'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '1.1.2-free'
    }

    signingConfigs {
        release {
            storeFile file('escrevemais.jks')
            storePassword 'escrevemais123'
            keyAlias 'escrevemais'
            keyPassword 'escrevemais123'
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
